package warlock

import (
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

// Real tooltip (from item DB, e.g. Deathmist Belt):
// (2) Set: +10 Resistances/+200 Armor.
// (4) Set: When struck in combat has a chance of causing the attacker to flee in terror for 2 seconds.
// (6) Set: Increases damage and healing done by magical spells and effects by up to 23.
// (8) Set: +10 Resistances/+200 Armor.
var ItemSetDeathmistRaiment = core.NewItemSet(core.ItemSet{
	Name: "Deathmist Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
		// (4) Set: chance to fear the attacker for 2s when struck. This is a defensive CC proc with no
		// damage/threat impact modeled in this sim (target fear/flee behavior on hit-taken isn't
		// implemented anywhere in the sim), so there is nothing to do here.
		4: func(agent core.Agent) {},
		6: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStat(stats.SpellPower, 23)
		},
		8: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(10)
			c.AddStat(stats.Armor, 200)
		},
	},
})

// Real tooltip (from item DB, e.g. Felheart Bracers):
// (2) Set: Health or Mana gained from Drain Life and Drain Mana increased by 15%.
// (4) Set: Your pet gains 20 stamina and 130 spell resistance against all schools of magic.
// (6) Set: Mana cost of Shadow spells reduced by 15%.
// (8) Set: Increases spell damage by up to 20% of your Stamina.
var ItemSetFelheartRaiment = core.NewItemSet(core.ItemSet{
	Name: "Felheart Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		2: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Felheart Raiment (2pc)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					// Drain Life's self-heal is implemented as a separate tagged spell registered
					// alongside each rank of the damage spell; boost its output by 15%.
					drainLifeSpellIds := []int32{689, 699, 709, 7651, 11699, 11700}
					for _, spellId := range drainLifeSpellIds {
						if healingSpell := warlock.GetSpell(core.ActionID{SpellID: spellId}.WithTag(1)); healingSpell != nil {
							healingSpell.DamageMultiplier *= 1.15
						}
					}
					// Drain Mana is not implemented anywhere in this sim, so that portion of the
					// bonus has no effect to apply.
				},
			})
		},
		4: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			for _, pet := range warlock.BasePets {
				pet.AddStat(stats.Stamina, 20)
				pet.AddResistances(130)
			}
		},
		6: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Shadow Cost Reduction (Felheart Raiment)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Spellbook {
						if spell.SpellSchool.Matches(core.SpellSchoolShadow) && spell.Cost != nil {
							spell.Cost.Multiplier -= 15
						}
					}
				},
			})
		},
		8: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.AddStatDependency(stats.Stamina, stats.SpellPower, 0.20)
		},
	},
})

// Real tooltip (from item DB, e.g. Nemesis Bracers):
// (2) Set: Doubles both cooldown and the amount of Mana awarded by your Life Tap.
// (4) Set: Reduces the threat generated by your Destruction spells by 10%.
// (6) Set: Critical strikes heal you for 15% of the damage dealt.
// (8) Set: Your Destruction spells deal 5% more damage when the target has less health(percentage) than you.
var ItemSetNemesisRaiment = core.NewItemSet(core.ItemSet{
	Name: "Nemesis Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		2: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Nemesis Raiment (2pc)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warlock.LifeTapManaMultiplier = 2
					// Life Tap has no cooldown implemented in this sim (only a GCD), so doubling its
					// cooldown has nothing to apply.
				},
			})
		},
		4: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Decreased Destruction Threat (Nemesis Raiment)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Spellbook {
						if spell.Flags.Matches(WarlockFlagDestruction) {
							spell.ThreatMultiplier *= 0.90
						}
					}
				},
			})
		},
		6: func(agent core.Agent) {
			c := agent.GetCharacter()
			healthMetrics := c.NewHealthMetrics(core.ActionID{SpellID: 27817})
			core.MakePermanent(c.RegisterAura(core.Aura{
				Label: "Nemesis Raiment (6pc)",
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if result.DidCrit() && result.Damage > 0 {
						c.GainHealth(sim, result.Damage*0.15, healthMetrics)
					}
				},
			}))
		},
		8: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Nemesis Raiment (8pc)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					// Wrap each Destruction spell's ApplyEffects so it deals 5% more damage whenever
					// the target is at a lower health percentage than the caster. This covers direct-hit
					// Destruction damage; periodic (DoT) ticks are not affected by this wrapper.
					for _, spell := range warlock.Spellbook {
						if !spell.Flags.Matches(WarlockFlagDestruction) || spell.ApplyEffects == nil {
							continue
						}
						oldApplyEffects := spell.ApplyEffects
						spell.ApplyEffects = func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
							if target.HasHealthBar() && target.CurrentHealthPercent() < warlock.CurrentHealthPercent() {
								spell.DamageMultiplier *= 1.05
								oldApplyEffects(sim, target, spell)
								spell.DamageMultiplier /= 1.05
							} else {
								oldApplyEffects(sim, target, spell)
							}
						}
					}
				},
			})
		},
	},
})

// Real tooltip (from item DB, e.g. Kezan's Unstoppable Taint):
// (2) Set: Increases the damage of Corruption by 3%.
// (3) Set: Increases damage and healing done by magical spells and effects by up to 27.
// (5) Set: Decreases the cooldown of Death Coil by 20 sec.
var ItemSetDemoniacsThreads = core.NewItemSet(core.ItemSet{
	Name: "Demoniac's Threads",
	Bonuses: map[int32]core.ApplyEffect{
		2: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Improved Corruption (Demoniac's Threads)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Corruption {
						spell.DamageMultiplierAdditive += 0.03
					}
				},
			})
		},
		3: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.AddStat(stats.SpellPower, 27)
		},
		5: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Improved Death Coil (Demoniac's Threads)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.DeathCoil {
						spell.CD.Duration -= 20 * time.Second
					}
				},
			})
		},
	},
})

// NOTE: This set's items (ids 21334/21335/... "Doomcaller's Circlet/Footwraps/Mantle/Robes/Trousers")
// are present in assets/db_inputs/custom_items.json with a correct setName and tooltip, but are not
// present in assets/db_inputs/included_items.json, so they don't resolve to any items in the generated
// database and this set can never actually become active. This is a content-gap, not a setName/code
// bug - flagging per audit instructions, not modifying included_items.json.
//
// Real tooltip (from custom_items.json, e.g. Doomcaller's Robes):
// (3) Set: 5% increased damage on your Immolate spell.
// (5) Set: Reduces the mana cost of Shadow Bolt by 15%.
// The Go code below already matches this tooltip.
var ItemSetDoomcallersAttire = core.NewItemSet(core.ItemSet{
	Name: "Doomcaller's Attire",
	Bonuses: map[int32]core.ApplyEffect{
		3: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Doomcaller Immolate Bonus",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Immolate {
						spell.BaseDamageMultiplierAdditive += 0.05
					}
				},
			})
		},
		5: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Doomcaller Reduced Shadow Bolt Cost",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.ShadowBolt {
						spell.Cost.Multiplier -= 15
					}
				},
			})
		},
	},
})

// NOTE: Like Doomcaller's Attire above, this set's pieces (e.g. id 22504 "Plagueheart Robe") have a
// correct setName/tooltip in assets/db_inputs/custom_items.json but are absent from
// assets/db_inputs/included_items.json, so this set never resolves to any items in the generated
// database and can never actually become active. Content-gap, not a code/data bug - flagging only.
//
// Real tooltip (from custom_items.json, e.g. Plagueheart Robe):
// (2) Set: Your Shadow Bolts now have a chance to heal you for 270 to 330.
// (4) Set: Increases damage caused by your Corruption by 12%.
// (6) Set: Your spell critical hits generate 25% less threat. In addition, Corruption, Immolate,
//
//	Curse of Agony, and Siphon Life generate 25% less threat.
//
// (8) Set: Reduces health cost of your Life Tap by 12%.
var ItemSetPlagueheartRaiment = core.NewItemSet(core.ItemSet{
	Name: "Plagueheart Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		// (2) Set: proc-heal on Shadow Bolt crit/cast is not implemented - left as a no-op since this
		// set is currently unreachable content (see note above).
		2: func(agent core.Agent) {},
		4: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Corruption (Plagueheart Raiment)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Corruption {
						spell.DamageMultiplierAdditive += 0.12
					}
				},
			})
		},
		6: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Plagueheart",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Corruption {
						spell.ThreatMultiplier *= 0.75
					}

					for _, spell := range warlock.Immolate {
						spell.ThreatMultiplier *= 0.75
					}

					for _, spell := range warlock.CurseOfAgony {
						spell.ThreatMultiplier *= 0.75
					}

					for _, spell := range warlock.SiphonLife {
						spell.ThreatMultiplier *= 0.75
					}

					// TODO: Spell crit threat? Do we care?
				},
			})
		},
		// (8) Set: Reduces health cost of Life Tap by 12% - Life Tap's health cost and mana restored
		// are computed from the same damage result in this sim (see lifetap.go), so reducing only the
		// health-cost side isn't supported without a larger refactor. Left as a no-op; this set is
		// currently unreachable content anyway (see note above).
		8: func(agent core.Agent) {},
	},
})
