syntax = "proto3";
package proto;

option go_package = "./proto";

message RogueTalents {
	// Assassination
	int32 improved_eviscerate = 1;
	int32 remorseless_attacks = 2;
	int32 malice = 3;
	int32 ruthlessness = 4;
	int32 seek_and_destroy = 5;
	int32 exhaustion = 6;
	bool relentless_strikes = 7;
	int32 lethality = 8;
	int32 coup_de_grace = 9;
	int32 seal_fate = 10;
	int32 death_mark = 11;
	int32 bloodthirsty = 12;
	int32 vitality = 13;
	bool cold_blood = 14;
	int32 improved_kidney_shot = 15;
	int32 total_control = 16;
	int32 improved_poisons = 17;
	int32 cold_blooded = 18;
	int32 gaining_an_advantage = 19;
	bool vigor = 20;

	// Combat
	int32 improved_gouge = 21;
	int32 improved_sinister_strike = 22;
	int32 bitter_experience = 23;
	int32 improved_backstab = 24;
	int32 deflection = 25;
	int32 precision = 26;
	int32 improved_sprint = 27;
	int32 improved_kick = 28;
	bool riposte = 29;
	int32 dual_wield_specialization = 30;
	int32 dazing_bolts = 31;
	int32 steadfast_determination = 32;
	int32 weapon_expertise = 33;
	int32 survivor = 34;
	bool blade_flurry = 35;
	int32 physical_prowess = 36;
	int32 combat_rush = 37;
	int32 combat_expertise = 38;
	int32 aggression = 39;
	bool adrenaline_rush = 40;

	// Subtlety
	int32 improved_sap = 41;
	int32 master_of_deception = 42;
	int32 opportunity = 43;
	int32 initiative = 44;
	int32 sleight_of_hand = 45;
	int32 thug_life = 46;
	int32 setup = 47;
	bool camouflage = 48;
	int32 improved_ambush = 49;
	int32 connivery = 50;
	int32 heightened_senses = 51;
	int32 elusiveness = 52;
	int32 shadow_cut = 53;
	bool cloak_of_shadows = 54;
	int32 dirty_deeds = 55;
	bool hemorrhage = 56;
	int32 brigandage = 57;
	int32 deadliness = 58;
	int32 enveloping_shadows = 59;
	bool preparation = 60;
}

message RogueOptions {

}

message Rogue {
	message Rotation {
	}

	RogueOptions options = 2;
}

message TankRogue {
	message Rotation {
	}

	RogueOptions options = 2;
}
