syntax = "proto3";
package proto;

option go_package = "./proto";

message WarlockTalents {
	// Affliction
	int32 fel_concentration = 1;
	int32 improved_life_tap = 2;
	int32 jinx = 3;
	int32 improved_drain = 4;
	int32 suppression = 5;
	int32 improved_curse_of_agony = 6;
	int32 dread = 7;
	int32 black_speech = 8;
	bool amplify_curse = 9;
	int32 improved_corruption = 10;
	int32 improved_drain_soul = 11;
	int32 nightfall = 12;
	int32 herald_of_woe = 13;
	bool siphon_life = 14;
	int32 withering_shroud = 15;
	bool death_and_decay = 16;
	int32 shadow_mastery = 17;
	int32 inevitable_doom = 18;
	int32 prolonged_misery = 19;
	bool defiler = 20;

	// Demonology
	int32 improved_imp = 21;
	int32 improved_healthstone = 22;
	int32 unholy_power = 23;
	int32 improved_health_funnel = 24;
	int32 improved_voidwalker = 25;
	int32 master_conjuror = 26;
	int32 demonic_embrace = 27;
	int32 damned_vanguard = 28;
	int32 improved_succubus = 29;
	bool fel_domination = 30;
	int32 demonic_onslaught = 31;
	int32 fel_intellect = 32;
	int32 master_summoner = 33;
	int32 fel_stamina = 34;
	int32 improved_felhunter = 35;
	bool soul_link = 36;
	int32 improved_enslave_demon = 37;
	int32 master_demonologist = 38;
	int32 fel_pact = 39;
	bool demonic_sacrifice = 40;

	// Destruction
	int32 destructive_reach = 41;
	int32 bane = 42;
	int32 aftermath = 43;
	int32 intensity = 44;
	int32 devastation = 45;
	int32 demonic_power = 46;
	int32 cataclysm = 47;
	int32 ruin = 48;
	int32 feeding_demons = 49;
	bool shadowburn = 50;
	int32 improved_shadow_bolt = 51;
	int32 sadism = 52;
	int32 pyroclasm = 53;
	bool conflagrate = 54;
	int32 bring_the_pain = 55;
	bool mayhem = 56;
	int32 shadowstorm = 57;
	int32 emberstorm = 58;
	bool improved_immolate = 59;
	bool shock_and_awe = 60;
}

message WarlockRotation {
}

message WarlockOptions {
	enum Summon {
		NoSummon = 0;
		Imp = 1;
		Voidwalker = 2;
		Succubus = 3;
		Felhunter = 4;
	}

	enum Armor {
		NoArmor = 0;
		DemonArmor = 1;
	}

	enum WeaponImbue {
		NoWeaponImbue = 0;
		Spellstone = 1;
		Firestone = 2;
	}

	enum MaxFireboltRank {
		NoMaximum = 0;
		Rank1 = 1;
		Rank2 = 2;
		Rank3 = 3;
		Rank4 = 4;
		Rank5 = 5;
		Rank6 = 6;
		Rank7 = 7;
		Rank8 = 8;
	}

	Armor armor = 1;
	Summon summon = 2;
	WeaponImbue weapon_imbue = 3;
	MaxFireboltRank max_firebolt_rank = 4;
	bool pet_pool_mana = 5;
}

message Warlock {
	WarlockOptions options = 2;
}

message TankWarlock {
	WarlockOptions options = 2;
}
