syntax = "proto3";
package proto;

option go_package = "./proto";

message WarriorTalents {
	// Arms
	int32 improved_heroic_strike = 1;
	int32 tactical_mastery = 2;
	int32 deflection = 3;
	int32 improved_charge = 4;
	int32 duelist = 5;
	int32 improved_thunder_clap = 6;
	int32 improved_hamstring = 7;
	bool anger_management = 8;
	int32 improved_rend = 9;
	int32 impale = 10;
	int32 weapon_expertise = 11;
	int32 improved_battle_stance = 12;
	int32 deep_wounds = 13;
	bool sweeping_strikes = 14;
	int32 two_handed_weapon_specialization = 15;
	int32 maim = 16;
	int32 para_bellum = 17;
	int32 dog_of_war = 18;
	bool mortal_strike = 19;
	int32 improved_mortal_strike = 20;

	// Fury
	int32 combat_endurance = 21;
	int32 booming_voice = 22;
	int32 cruelty = 23;
	int32 improved_combat_shouts = 24;
	int32 unbridled_wrath = 25;
	int32 precision = 26;
	bool piercing_howl = 27;
	int32 blood_craze = 28;
	int32 cleaving = 29;
	int32 improved_execute = 30;
	int32 enrage = 31;
	int32 slamcraft = 32;
	int32 inner_rage = 33;
	bool death_wish = 34;
	int32 interceptor = 35;
	int32 flurry = 36;
	int32 berserkers_blood = 37;
	int32 improved_berserker_stance = 38;
	bool bloodthirst = 39;
	int32 improved_bloodthirst = 40;

	// Protection
	int32 improved_bloodrage = 41;
	int32 toughness = 42;
	int32 anticipation = 43;
	int32 shield_specialization = 44;
	int32 mocker = 45;
	int32 improved_defensive_stance = 46;
	bool last_stand = 47;
	int32 shield_mastery = 48;
	int32 defiance = 49;
	bool concussion_blow = 50;
	int32 blade_mail = 51;
	int32 shield_assault = 52;
	int32 one_handed_weapon_specialization = 53;
	int32 iron_will = 54;
	bool shield_toss = 55;
	int32 training_and_discipline = 56;
	int32 improved_shield_wall = 57;
	int32 vitality = 58;
	int32 butterfly_style = 59;
	bool constitution = 60;
}

enum WarriorShout {
	WarriorShoutNone = 0;
	WarriorShoutBattle = 1;
	WarriorShoutCommanding = 2;
}

enum WarriorStance {
	WarriorStanceNone = 0;
	WarriorStanceBattle = 1;
	WarriorStanceDefensive = 2;
	WarriorStanceBerserker = 3;
	WarriorStanceGladiator = 4;
}

message Warrior {
	message Rotation {
	}

	message Options {
		reserved 2;
		reserved "use_recklessness";

		double starting_rage = 1;
		bool stance_snapshot = 6;
		int32 queue_delay = 8;

		WarriorShout shout = 3;
		WarriorStance stance = 7;
	}
	Options options = 3;
}

message TankWarrior {
	message Rotation {
	}

	message Options {
		double starting_rage = 1;
		bool stance_snapshot = 6;
		int32 queue_delay = 8;

		WarriorShout shout = 3;
		WarriorStance stance = 7;
	}
	Options options = 3;
}
